/**
 * Every BFF route's envelope, pinned (audit Q-A8, Phase 4).
 *
 * bffEnvelopes.golden.json records, for each of the routes migrated onto
 * callBackend in Phase 4, what the route answered BEFORE the migration under
 * every scenario in the matrix (bffTestkit.SCENARIOS): status, JSON body and
 * content type. The golden was generated by running the pre-migration route
 * files under this same kit, so a green run here means the migration changed
 * no status, no code and no user-facing string — copy is founder-held
 * (CLAUDE.md: user-facing copy needs sign-off).
 *
 * To change an envelope on purpose (a signed-off copy decision), change the
 * golden entry in the same PR and say so. Never regenerate the file to make a
 * red run green.
 *
 * Two cells are deliberately not in the golden:
 *   - the eight former proxyJson routes under `no_url`: proxyJson had no
 *     configuration guard and called "undefined/…"; callBackend answers 502
 *     BACKEND_UNAVAILABLE like every other route.
 *   - a signed-out caller on an unconfigured backend URL: thirteen routes used
 *     to answer 502 before 401 and now answer 401 first. A deployment with no
 *     backend URL is broken either way.
 */
import { describe, expect, it, vi } from "vitest";
import {
  absolute,
  LAB_EVENTS_FILE,
  runScenario,
  SCENARIOS,
  LAB_EVENTS_SCENARIOS,
  type BodyKind,
  type Outcome,
  type RouteSpec,
  type Scenario,
} from "@/app/api/_lib/bffTestkit";
import golden from "./bffEnvelopes.golden.json";

const ctx = vi.hoisted(() => ({
  headerToken: null as string | null,
  cookieToken: null as string | null,
}));

vi.mock("server-only", () => ({}));
vi.mock("next/headers", () => ({
  headers: async () =>
    new Headers(ctx.headerToken ? { Authorization: `Bearer ${ctx.headerToken}` } : {}),
  cookies: () => ({ getAll: () => [], set: () => {}, get: () => undefined }),
}));
vi.mock("next/cache", () => ({ revalidatePath: () => {} }));
vi.mock("@supabase/ssr", () => ({
  createServerClient: () => ({
    auth: {
      getUser: async () => ({ data: { user: ctx.cookieToken ? { id: "u1" } : null } }),
      getSession: async () => ({
        data: { session: ctx.cookieToken ? { access_token: ctx.cookieToken } : null },
      }),
    },
  }),
}));

type Pinned = { status: number; body: unknown; contentType: string | null; cacheControl: string | null } | { throws: string };
const GOLDEN = golden as Record<string, Record<string, Pinned>>;
const SCENARIO_BY_NAME = new Map<string, Scenario>(
  [...SCENARIOS, ...LAB_EVENTS_SCENARIOS].map((s) => [s.name, s])
);
const MATRIX_NAMES = new Set(SCENARIOS.map((s) => s.name));

const importRoute = (file: string) => import(/* @vite-ignore */ absolute(file));

function observed(outcome: Outcome): Pinned {
  return {
    status: outcome.status,
    body: outcome.body,
    contentType: outcome.contentType,
    cacheControl: outcome.cacheControl,
  };
}

describe("BFF envelopes are the ones each route shipped with", () => {
  vi.spyOn(console, "error").mockImplementation(() => {});
  vi.spyOn(console, "log").mockImplementation(() => {});
  vi.spyOn(console, "warn").mockImplementation(() => {});

  for (const [key, cells] of Object.entries(GOLDEN)) {
    const [file, handler, bodyKind] = key.split("#");
    const spec: RouteSpec = { file, handler, bodyKind: bodyKind as BodyKind };
    it(key, async () => {
      for (const [name, pinned] of Object.entries(cells)) {
        const base = SCENARIO_BY_NAME.get(name);
        expect(base, `unknown scenario ${name}`).toBeDefined();
        const scenario: Scenario =
          file === LAB_EVENTS_FILE && MATRIX_NAMES.has(name) ? { ...base!, aborted: true } : base!;
        let actual: Pinned;
        try {
          actual = observed(await runScenario(ctx, spec, scenario, importRoute));
        } catch (err) {
          actual = { throws: err instanceof Error ? `${err.name}: ${err.message}` : String(err) };
        }
        expect(actual, `${key} under ${name}`).toEqual(pinned);
      }
    }, 60_000);
  }
});
