/* -------------------------------------------------------------------------- */
/*  coachAuditData — per-student analytics for the interactive audit view     */
/*                                                                            */
/*  GET /api/v2/coach/students/<id>/audit-data (BE #108, coach-gated)         */
/*    → { performance_under_feeling, stress_as_fuel }                         */
/*                                                                            */
/*  Sections are individually nullable: when a student has insufficient data  */
/*  to compute a section, the BE returns null for it and the FE hides it.     */
/* -------------------------------------------------------------------------- */

export type Feeling = "nervous" | "excited" | "calm" | "unsure";

export interface FeelingBucket {
  feeling: Feeling;
  /** Composite stickiness score (0–1). */
  score: number;
  /** Number of recordings with this feeling. */
  n: number;
}

export interface PerformanceUnderFeeling {
  buckets: FeelingBucket[];
  /** Coach-editable headline, pre-generated by BE. null = insufficient data. */
  headline: string | null;
  /** The feeling with the highest composite score. */
  topFeeling: Feeling | null;
}

export interface StressAsFuel {
  /** Percentage (0–100) of stress-coded takes where performance was above avg. */
  pct: number;
  /** Coach-editable headline, pre-generated by BE. */
  headline: string | null;
}

export interface CoachAuditData {
  performanceUnderFeeling: PerformanceUnderFeeling | null;
  stressAsFuel: StressAsFuel | null;
}

function pickFeeling(v: unknown): Feeling | null {
  if (v === "nervous" || v === "excited" || v === "calm" || v === "unsure") return v;
  return null;
}

function mapBucket(raw: unknown): FeelingBucket | null {
  if (!raw || typeof raw !== "object") return null;
  const r = raw as Record<string, unknown>;
  const feeling = pickFeeling(r.feeling);
  if (!feeling) return null;
  return {
    feeling,
    score: typeof r.score === "number" ? r.score : 0,
    n: typeof r.n === "number" ? r.n : 0,
  };
}

function mapPerformanceUnderFeeling(raw: unknown): PerformanceUnderFeeling | null {
  if (!raw || typeof raw !== "object") return null;
  const r = raw as Record<string, unknown>;
  const buckets = Array.isArray(r.buckets)
    ? r.buckets.map(mapBucket).filter((b): b is FeelingBucket => b !== null)
    : [];
  if (buckets.length === 0) return null;
  return {
    buckets,
    headline: typeof r.headline === "string" && r.headline.length > 0 ? r.headline : null,
    topFeeling: pickFeeling(r.top_feeling),
  };
}

function mapStressAsFuel(raw: unknown): StressAsFuel | null {
  if (!raw || typeof raw !== "object") return null;
  const r = raw as Record<string, unknown>;
  if (typeof r.pct !== "number") return null;
  return {
    pct: r.pct,
    headline: typeof r.headline === "string" && r.headline.length > 0 ? r.headline : null,
  };
}

export function mapCoachAuditData(raw: unknown): CoachAuditData {
  const r = (raw && typeof raw === "object" ? raw : {}) as Record<string, unknown>;
  return {
    performanceUnderFeeling: mapPerformanceUnderFeeling(r.performance_under_feeling),
    stressAsFuel: mapStressAsFuel(r.stress_as_fuel),
  };
}

export async function fetchCoachAuditData(userId: string): Promise<CoachAuditData | null> {
  let res: Response;
  try {
    res = await fetch(
      `/api/v2/coach/students/${encodeURIComponent(userId)}/audit-data`,
      { credentials: "include", cache: "no-store" }
    );
  } catch {
    return null;
  }
  if (!res.ok) return null;
  return mapCoachAuditData(await res.json().catch(() => null));
}
